### ISSUE TITLE
Add SVG comments

### ISSUE THREAD

**Issue by tjvr** [tjvr/scratchblocks#103]
I nearly forgot about these

(Do we really need them anyway?!)

**Comment by liam4** [comment]
It'd probably be nice if there was some kind of maximum width to comments...

![comments](https://cloud.githubusercontent.com/assets/9948030/14424940/5b0451e4-ffba-11e5-85aa-b810ab277b8f.png)

**Comment by tjvr** [comment]
@liam4 Maybe. In an ideal world, we might have proper multi-line comments, and layout those to the right of the script like Scratch does, so they don't overlap any of the other blocks.

As it is, this is the same behaviour as the current renderer, and no-one's complained about that yet. So I'm gonna leave this.

**Comment by oisintheblue** [comment]
what about height? it would be like this:
say [Amogus] // this is a comment,
hi
end of comment. //
