### ISSUE TITLE
Empty boolean slots do not work

### ISSUE THREAD

**Issue by jupiterio** [tjvr/scratchblocks#104]
You probably know this, but I feel like it would be better for everyone if there where to be an issue about it here.

This is what appears in the testing page's console when you try to do it:
```
scratchblocks-min.js:9 Uncaught Assertion failed!
	assert @ scratchblocks-min.js:9
	Input.fromAST @ scratchblocks-min.js:9
	(anonymous function) @ scratchblocks-min.js:10
	Block.fromAST @ scratchblocks-min.js:10
	Script.fromAST @ scratchblocks-min.js:10
	parse @ scratchblocks-min.js:10
	objUpdated @ (index):244
	(anonymous function) @ (index):158
	(anonymous function) @ codemirror-compressed.js:31
	Hc @ codemirror-compressed.js:30
	Ic @ codemirror-compressed.js:30
	(anonymous function) @ codemirror-compressed.js:30
```

**Comment by tjvr** [comment]
Please provide code examples when reporting :)

I didn't know about that, actually—thanks!

**Comment by Airhogs777** [comment]
I just stumbled upon this too. Here's one example:
`if < > then`
and here's an exmple from the Snap_!_ section of the wiki:
`<<>>`
neither renders at all

**Comment by BlueDome77** [comment]
It renders the "wait until" block properly but if you change the color the empty Boolean slot doesn't appear:

![scratchblocks-4](https://github.com/scratchblocks/scratchblocks/assets/135789443/2d62abfb-5f9e-4543-ad68-a0399c780dce)


You can create a fake empty slot by putting this code inside the Boolean: `⠀⠀:: #4582d4` ← Copy the entire code!

![scratchblocks-3](https://github.com/scratchblocks/scratchblocks/assets/135789443/635df24d-7859-4760-aede-b0ef07bb7926)
