### ISSUE TITLE
Custom Hex Block Colors

### ISSUE THREAD

**Issue by Airhogs777** [tjvr/scratchblocks#108]
This would be low-priority since it's just for fun, but since you're rewriting the parser, would it be possible to allow hex values for block colors in the following format?
`block name :: #00f`

**Comment by tjvr** [comment]
Really easily. Thanks!

**Comment by tjvr** [comment]
Example: pink! All the pink
```
when flag clicked
say [Hello there!] :: #ff4fc3
move (10) steps ::  #ff4fc3
forever :: #ff4fc3
stamp  :: #ff4fc3
```
