### ISSUE TITLE
Escape Characters 

### ISSUE THREAD

**Issue by Airhogs777** [tjvr/scratchblocks#109]
For the new parser, you could consider adding character escapes for scratchblocks syntax. Some cases I can imagine are these:
```
set [right-square-bracket v] to [\]] // I've actually run into this one 
define user\::control // I've seen this name scheme for variables and things
say [the letter \v]
```

**Comment by tjvr** [comment]
Duplicate of #18 (which is already fixed in the new parser).
 
As for `\::`, I considered this but decided not to implement it at
this time.

**Comment by Airhogs777** [comment]
That's awesome! Sorry, I should've checked for duplicates
