### ISSUE TITLE
Custom definitions inconsistent for inline stacks

### ISSUE THREAD

**Issue by Airhogs777** [tjvr/scratchblocks#110]
When a curly-bracketed block is on its own line, it detects definitions correctly. When it's inline, it renders as obsolete.
```
define f
say {f} // f is obsolete
{f} // f is custom
```
Note: I haven't played with Snap! much, so I don't know which behavior makes it easier to notate

**Comment by tjvr** [comment]
We'll fix this in the new parser.

**Comment by tjvr** [comment]
Having looked at this: the current behaviour of a block `{f}` on its own line parsing the same as a normal block `f` is completely insane, and will go away.

The way I'm going to implement custom block recognition, custom blocks inside rings shouldn't be an issue, so I'm going to close this. Thanks for reporting!

**Comment by liam4** [comment]
Will this break old scratchblocks usages? (not that it makes any sense - I agree - but it _may_ have been used on the forums occasionally..)

**Comment by tjvr** [comment]
@liam4 Maybe. I've never seen it used. Regardless, the v3/3.1 release intentionally breaks backwards compatibility.

**Comment by Airhogs777** [comment]
> Regardless, the v3/3.1 release intentionally breaks backwards compatibility.

How so? Besides being written better and working more consistently, how will the new parser be different?
