### ISSUE TITLE
Stack ring blocks should have a cap block cut out

### ISSUE THREAD

**Issue by jupiterio** [tjvr/scratchblocks#112]
In Snap! (and scratchblocks, not v3), stack ring blocks have a cap block cut out instead of a normal stack block cut out, always, even when a normal stack block is inside it.
[Snap!](http://i.cubeupload.com/bXEhoS.png)
[Old Scratchblocks](http://scratchblocks.github.io/#(%7B%7D%E2%96%B6%3A%3Aring%20grey)%0A(%7Bsay%20%5Bexample%5D%7D%E2%96%B6%3A%3Aring%20grey))
[NuScratchblocks](http://scratchblocks.github.io/v3/#(%7B%7D%E2%96%B6%3A%3Aring%20grey)%0A(%7Bsay%20%5Bexample%5D%7D%E2%96%B6%3A%3Aring%20grey))

**Comment by tjvr** [comment]
This is kind of a pain, so I decided it wasn't important. :)
