### ISSUE TITLE
More "modern" technical design?

### ISSUE THREAD

**Issue by as-com** [tjvr/scratchblocks#113]
Ideas:

- ES6 modules, using Rollup or Closure Compiler to build
- React-based website using [Preact](https://github.com/developit/preact) (more efficient/scalable to build)
- Encapsulation into a React component or just making a React renderer

**Comment by tjvr** [comment]
No thanks. :)

**Comment by tjvr** [comment]
@as-com I sent you an email with some further feedback on this.

**Comment by liam4** [comment]
&lt;small&gt;Aww, not a public email? :(&lt;/small&gt;

**Comment by as-com** [comment]
@liam4 Basically he said that he doesn't like React and does not trust using these compilers and new ES6 features.

**Comment by tjvr** [comment]
Basically, I'm a grumpy old person :P 

I do trust compilers! I'm just too impatient to use them. My main point was that I'd rather spend time making things, than fiddling with build tools...
