### ISSUE TITLE
SVG Rendering broken in IE9-IE11, Safari 6.0

### ISSUE THREAD

**Issue by as-com** [tjvr/scratchblocks#114]
IE11:
![](https://www.browserstack.com/screenshots/33c1c3f656ea944030f4dbd557c62b8dcaf5755e/win8.1_ie_11.0.png)

Safari 6.0:
![](https://www.browserstack.com/screenshots/33c1c3f656ea944030f4dbd557c62b8dcaf5755e/maclion_safari_6.0.png)

For IE11, I could not find any errors in the console.

**Comment by tjvr** [comment]
Oh dear. Thanks for checking this in IE!

Any idea how to fix this? :)

**Comment by tjvr** [comment]
Looks like IE is failing to add the SVG element to the page.

I also found this:

![screen shot 2016-04-15 at 01 24 05](https://cloud.githubusercontent.com/assets/639289/14547751/e2a2934a-02a8-11e6-886c-393e7f0f69ff.png)

**Comment by tjvr** [comment]
Oops, [classList](http://caniuse.com/#search=classlist) isn't supported in those browsers.
