### ISSUE TITLE
Add "Export PNG" button

### ISSUE THREAD

**Issue by tjvr** [tjvr/scratchblocks#115]
I think this would be useful. I might wait until someone else requests it first.

Possibly using canvg to render the SVG?

I really hope we don't end up wanting `@1x` and `@2x` options...

**Comment by Airhogs777** [comment]
If you serve files based on scratchblocks in the URL you may find that the project turns into a CDN

**Comment by arve0** [comment]
Also relevant: https://www.npmjs.com/package/svg-to-image

**Comment by tjvr** [comment]
@arve0 Thanks! I hadn't realised you can just draw an SVG onto a canvas using the native renderer :-)

**Comment by tjvr** [comment]
Added. Let me know if it doesn't work for you!
