### ISSUE TITLE
SVG rendering in IE9

### ISSUE THREAD

**Issue by tjvr** [tjvr/scratchblocks#116]
The bevel filter doesn't work.
<img width="986" alt="screen shot 2016-04-15 at 19 17 16" src="https://cloud.githubusercontent.com/assets/639289/14571362/c0e3c92a-0340-11e6-852c-7f2f5b438ea0.png">
Options:
- Embed canvg and try rendering the SVG in JS
- Fallback to using borders or some other way of faking the effect
- Live with it: the colors and text are clearly visible, so the functionality of the graphic isn't affected.

Thoughts?

**Comment by tjvr** [comment]
@as-com What do you think? :)

**Comment by as-com** [comment]
I think it still looks better than v2, even without the filters, but it might be helpful to fall back to some inner stroke that is rgba(255, 255, 255, 64) for the top and left, and rgba(0, 0, 0, 64) for the bottom and right. 

Thankfully, detecting SVG filter support is startling easy in JavaScript:
```js
var supportsfilter = typeof SVGFEColorMatrixElement !== undefined && 
                     SVGFEColorMatrixElement.SVG_FECOLORMATRIX_TYPE_SATURATE==2;
```
(from https://stackoverflow.com/questions/9739955/feature-detecting-support-for-svg-filters)

**Comment by tjvr** [comment]
@as-com Would you like to write a patch for this? :-)
