### ISSUE TITLE
Add Scratch 1.4 blocks

### ISSUE THREAD

**Issue by tjvr** [tjvr/scratchblocks#117]
The previous parser supported the following:
```
if <>
forever if <>
stop script
stop all
switch to costume %m.costume
switch to background %m.backdrop
next background
background #
loud?
```
I'd like to remove these: we should encourage people to use the 2.0 versions of blocks. (And they might cause issues with the backpack plugin.) However, this might break existing scripts.

**Comment by liam4** [comment]
Render as `:: undefined` (or whatever the error color is) with the old block shapes (i.e. `:: cstart` etc) maybe?

**Comment by tjvr** [comment]
@liam4 That's a uniquely weird solution. I like it xD

**Comment by Airhogs777** [comment]
I think scratchblocks should try to stay descriptive of whatever code people are trying to represent, unlike with Tosh it's not scratchblocks' job to make sure people's code works.

Then again, most of the use cases for those older blocks would be on the old 1.4 forums anyway, so I doubt removing them will break anyone's code.
