### ISSUE TITLE
Reporters with inputs are considered variables

### ISSUE THREAD

**Issue by liam4** [tjvr/scratchblocks#120]
![demo](https://cloud.githubusercontent.com/assets/9948030/14582487/b2d80a48-03dc-11e6-8dbe-c763a0e376c6.png)

```
(foo eleven [input]) // should be ::undefined
<baz thirty two [abc]> // this is right

define jokes (translation) [hark] <again>
say (translation [42])  // should be ::undefined
say (hark [arg])  // should be ::undefined
say <again [ument]> // this is right
```

These should be `:: undefined`, right?

(EDIT: or is it `:: #F00` now?)

**Comment by tjvr** [comment]
> is it :: #F00 now?

You're thinking of `obsolete`; this is the same as the old parser.

**Comment by tjvr** [comment]
Fixed, thanks!
