### ISSUE TITLE
Backpack plugin

### ISSUE THREAD

**Issue by tjvr** [tjvr/scratchblocks#121]
@hardmath123 Are you interested in finishing this? :)

The bad news is that the API completely changed, so you probably need to rewrite some code.

The good news is that there's now a sane API, with a sane AST, and a post-render hook; and scratchblocks now includes all the block selectors, so you don't have to manually translate them. So you shouldn't have very much new code to write.

Interested? :D

---

hardmath123 has finished the backpack plugin, see <https://github.com/scratchblocks/backpack>.

Still TODO (in `toJSON`):

- [x] Throw an exception for invalid selectors, rather than returning `""`
- [x] Add user id to `commands.js`—category should be obsolete
- [x] Add a `specialCase` to disambiguate the two "set pen color to _" blocks
- [ ] <s>Generate extension blocks correctly (I don't know how to do this; maybe we need to look at some projects)</s>

**Comment by Hardmath123** [comment]
Sure. The original code from many years ago lived scratchblocks2/backpack or some similarly-named repo if you want to take a look.

**Comment by tjvr** [comment]
@Hardmath123 You complained this was too hard, so I added `scratchblocks.toJSON(scripts)`, which should give you an array suitable for passing to Scratch. :)

**Comment by tjvr** [comment]
Specifically you might find a215e8b useful

**Comment by Hardmath123** [comment]
Yaaaaaay :D

**Comment by tjvr** [comment]
I think we just need to merge this now :)
