### ISSUE TITLE
Allow plural and singular for categories

### ISSUE THREAD

**Issue by jupiterio** [tjvr/scratchblocks#122]
Self explanatory. I've seen this bug people (including myself)
Not for all categories, but for all that would logically go in both ways
[Example code](http://scratchblocks.github.io/v3.1/#variables%20%3A%3A%20variables%0Avariables%20%3A%3A%20variable%0Alist%20%3A%3A%20lists%0Alist%20%3A%3A%20list%0Aoperators%20%3A%3A%20operators%0Aoperators%20%3A%3A%20operator%0Aevents%20%3A%3A%20events%0Aevents%20%3A%3A%20event%0Await%20(obsolete)%20secs%20%3A%3A%20obsolete%0Await%20(obsolete)%20secs%20%3A%3A%20undefined%0Agrey%20%3A%3A%20grey%0Agrey%20%3A%3A%20gray)

Also, related, please add undefined and gray too, for obsolete and grey respectively.

**Comment by tjvr** [comment]
The `::` override hacks are "advanced" features anyway, so I don't want to add aliases for them. Sorry!
