### ISSUE TITLE
Truncates exported SVGs at 189 bytes on FF45

### ISSUE THREAD

**Issue by ethanhs** [tjvr/scratchblocks#125]
When I went to export some SVGs (very excited to try it out). And, well, for every svg file I try to export, the file is truncated to be 189 bytes...
The most basic example for when I download `when gf clicked` :

```
<svg xmlns="http://www.w3.org/2000/svg" version="1.1" width="120" height="41"><defs><style><![CDATA[text{font-family:Lucida Grande,Verdana,Arial,DejaVu Sans,sans-serif;font-weight:700;fill:
```

It is missing a lot of important data. So I tried some other files. 
Below is a sampling (you will see they are all truncated at 189 bytes.
[block_templates.zip](https://github.com/tjvr/scratchblocks/files/222506/block_templates.zip)

I am using Firefox 45.0.2 on Windows 10. I tried it on chrome, and it seems to work fine.
No errors in the console either....

**Comment by tjvr** [comment]
Gosh, you're right! How odd.

**Comment by tjvr** [comment]
Theory: the `#` character is invalid in URLs.

**Comment by tjvr** [comment]
Looks like that fixed it :)

**Comment by ethanhs** [comment]
Looks good! Thanks. :smile:
