### ISSUE TITLE
Loops aren't padding the content properly

### ISSUE THREAD

**Issue by liam4** [tjvr/scratchblocks#128]
C blocks don't seem to be working..

![screenshot](http://u.cubeupload.com/liam/ScreenShot20160418at.png)

```
forever if <[4] = [8]>
	set instrument to (4)
	move (10) steps
end

forever
	set instrument to (4)
	move (10) steps
end

repeat (10)
	repeat (5)
		turn cw (15) degrees
	end
end
```

**Comment by tjvr** [comment]
Want to look into this for me? Hopefully it's not to do with the RTL code I just added...

**Comment by liam4** [comment]
I'll try going back a commit or two to see which caused this..

**Comment by liam4** [comment]
Hmm.. `git pull`ing and running the HTTP server locally didn't produce the problem..

On the branch `master`:

![master screenshot](https://cloud.githubusercontent.com/assets/9948030/14603754/fcc8c358-0545-11e6-98a4-07fa29d81755.png)

On the branch `new-parser`:

![new-parser screenshot](https://cloud.githubusercontent.com/assets/9948030/14603745/eaa1c580-0545-11e6-8aee-b73dcdfa8cbc.png)

**Comment by liam4** [comment]
Looks like it's working again.. perhaps one of the resources wasn't loaded properly on my end? Closing for now unless it happens again.
