### ISSUE TITLE
Won't correctly parse <(a)>(b)>

### ISSUE THREAD

**Issue by TheLogFather** [tjvr/scratchblocks#129]
This has been a longstanding issue, and I've avoided it so far in the forums by (ab)using normal brackets for booleans instead of > and <.

But now that we have booleans rendered with the correct triangular sides, it'd be nice to have vars/expressions in (the left side of) comparison blocks parsed correctly.

(It is somewhat tricky to get this right when the expression has several levels of nesting...)

**Comment by tjvr** [comment]
Hmm, both the old and the new parser have code to avoid this problem! Has this really been a bug for so long?

The relevant code is in https://github.com/tjvr/scratchblocks/blob/master/src/scratchblocks.js#L395 if you feel like sending a PR... :-)

**Comment by jupiterio** [comment]
I was taught to add spaces before and after the signs so that doesn't happen :P

Though, in the new parser, that happens with and without spaces.

**Comment by tjvr** [comment]
Should be fixed now. Let me know if you find any bugs still!

**Comment by TheLogFather** [comment]
Looking good!
Even seems to be working for quite complicated cases, with multiple types of nested operators, etc. :)
