### ISSUE TITLE
Allow coloring rings

### ISSUE THREAD

**Issue by NoMod-Programming** [tjvr/scratchblocks#132]
Right now, the scratchblocks parser doesn't support rings of different colors. So if you try to parse the following: 
`({Notice how the ring has no color whatsoever} ▸ ::0000FF)`
, the ring doesn't have a custom color. Obviously, this isn't a big issue, but it would concern the aesthetics of scratchblocks3, so that everything could have a custom color of some sort.

**Comment by tjvr** [comment]
You didn't use a proper hex color... you're missing a hash

**Comment by jupiterio** [comment]
Why not close it then? It works correctly with the hash :)

**Comment by tjvr** [comment]
Excellent! Glad to hear it.
