### ISSUE TITLE
Question: Translation reported 85.4%, but 100% at translate.scratch.mit.edu

### ISSUE THREAD

**Issue by arve0** [tjvr/scratchblocks#134]
When running `build_translations.py` I get this:

```
$ python build_translations.py
nb
nb is missing: turn %m.motor on for %n seconds
nb is missing: set light color to %n
nb is missing: play note %n for %n seconds
nb is missing: when tilted
nb is missing: tilt %m.xxx
nb is missing: . . .
nb is missing: %n @addInput
nb is missing: if %b
nb is missing: if %b
nb is missing: forever if %b
nb is missing: stop script
nb is missing: stop all
nb is missing: switch to costume %m.costume
nb is missing: next background
nb is missing: switch to background %m.backdrop
nb is missing: background #
nb is missing: loud?
nb: 85.4%
Wrote translations.js
```

Take the first line, `turn %m.motor on for %n seconds`, [it is translated](http://translate.scratch.mit.edu/nb/blocks/translate/#search=turn%20motor&sfields=source,target&unit=373485).

**Comment by liam4** [comment]
You might notice lots of those are the old, obsolete Scratch pre-2.0 blocks.

**Comment by arve0** [comment]
Aha, it's `turn %m.motor on for %n`**`secs`**.

**Comment by arve0** [comment]
In other words, [commands.js](https://github.com/tjvr/scratchblocks/blame/master/src/commands.js#L152) should be updated?

**Comment by tjvr** [comment]
Scratch 2.0 appears to have two different WeDo plugins:
<img width="199" alt="screen shot 2016-04-21 at 09 59 24" src="https://cloud.githubusercontent.com/assets/639289/14703447/c50b6c0e-07a7-11e6-8d01-0bdcef9d8be7.png">
`commands.js` includes both of them. It's possible that Pootle doesn't include those blocks in the 100% score?
