### ISSUE TITLE
Bug: "when green flag clicked" rendered in wrong language

### ISSUE THREAD

**Issue by arve0** [tjvr/scratchblocks#135]
**What happens**
Code renders to English.
![image](https://cloud.githubusercontent.com/assets/4810521/14680274/04c172de-071d-11e6-8b53-dc2b5bf7cf74.png)

**Expected**
Image should be in same language.

http://scratchblocks.github.io/#?lang=nb&script=n%C3%A5r%20gr%C3%B8nt%20flagg%20klikkes%0A

**Comment by arve0** [comment]
Duplicate, #131

**Comment by tjvr** [comment]
I've already fixed this in master, thanks!

**Comment by tjvr** [comment]
Now fixed!
