### ISSUE TITLE
Deploy to Scratch Forums

### ISSUE THREAD

**Issue by tjvr** [tjvr/scratchblocks#136]
See https://github.com/LLK/s2forums/pull/1340.

Still TODO:

- [x] Add [backpack plugin](https://github.com/scratchblocks/backpack)
- [x] Put back `palette` strings into translations.js (revert b758185?)
- [x] Unbreak `menu.js`
- [x] Merge https://github.com/LLK/s2forums/pull/1334
- [x] Finish scratchblocks v3.1

**Comment by liam4** [comment]
> Merge #1334

What do you mean by that? There certainly aren't 1334 pull requests (+ issues)..

**Comment by tjvr** [comment]
@liam4 Oops, that made more sense before I copy/pasted that todo list here. Fixed.

**Comment by tjvr** [comment]
If anyone wants to take responsibility for finishing/testing this, that would be fine by me. You can send a PR to the branch my PR is based on! The best way for testing it appears to be manual HTML rewriting and/or proxying s.m.e requests.
