### ISSUE TITLE
Escape syntax

### ISSUE THREAD

**Issue by tjvr** [tjvr/scratchblocks#138]
Ref #18, #109

It's now possible to escape `]` inside strings, using a backslash: `\]`

Should we allow escaping other characters too, eg `:`, `<`, `}` ?

**Comment by tjvr** [comment]
You can try this in the `escape` branch. Tell me if it breaks anything.

**Comment by Jonathan50** [comment]
Yes please!

**Comment by tjvr** [comment]
I hope this doesn't break anything.
