### ISSUE TITLE
v2 trimmed unicode space characters

### ISSUE THREAD

**Issue by Choco31415** [tjvr/scratchblocks#140]
If you don't know already, there exist multiple space characters in unicode. The Scratchblocks plugin seems to parse all non-normal space characters as part of a block. In this specific example, I use u+2002 (normal space is u+0020): http://i.cubeupload.com/rCzHZY.png

v2 of the Wiki scratchblocks plugin does not have this bug.

**Comment by tjvr** [comment]
Huh. This is because v2 uses `String::trim()`; whitespace characters inside a block [won't be ignored](http://scratchblocks.github.io/v2/#%E2%80%82%E2%80%82%E2%80%82%E2%80%82%E2%80%82foo%E2%80%82%E2%80%82%E2%80%82%E2%80%82%E2%80%82bar%20%E2%80%82%E2%80%82%E2%80%82%E2%80%82).

Does this matter?

**Comment by Choco31415** [comment]
I'm not 100% sure. It's hard to check the wikis to see where non-standard space characters are used. The one hot spot where I thought those would have been used, the Japanese wiki, does not seem to use any. I will bring this up in next week's Scratchclub and hopefully we'll get a clearer picture then. (I will do so with case-sensitivity.)
