### ISSUE TITLE
cend cap syntax

### ISSUE THREAD

**Issue by Airhogs777** [tjvr/scratchblocks#141]
In the new parser there's no way to specify that the end of a c-block is also a cap. Fix could be any of the following:

* a new block shape
* the option to use both block shape names
* `end :: cap` (which doesn't allow for text in the cend)

**Comment by tjvr** [comment]
> `end :: cap` (which doesn't allow for text in the cend)

This would make sense unless we fix #147.

NB. I think `cap` should be an argument to the cstart, anyway.

**Comment by jupiterio** [comment]
Related.
Any cend (either specified with :: or not), with cap, [bugs](http://scratchblocks.github.io/#if%20%3C%3E%20then%0A%0Aend%20%3A%3A%20cap%0A%0Afake%20C%20%3A%3A%20grey%20cstart%0A%20%20baz%20%3A%3A%20operators%0Aend%20%3A%3A%20cap%0A%0Atest%20%3A%3Acontrol%20cstart%0A%20%20say%20%5Bhello%5D%0Asee%20%5Basd%5D%20%3A%3Acelse%0A%20%20say%20%5Bit's%20me%5D%0Atesting%20%3C%3E%20%3A%3Acelse%0A%20%20say%20%5Bi%20was%20wondering%20if%20after%20all%20this%20years%20you'd%20like%20to%20meet%5D%0Aend%20%3A%3A%20cend%20cap%0A%0Athis%20should%20be%20outside%20%3A%3A%20cstart%0A%0A%3A%3A%20cend%20cap%0A%0Asay%20%5Bthere%20you%20are%5D). (It's better if you see it yourself, i'm not really sure how to explain it)

**Comment by Airhogs777** [comment]
> NB. I think `cap` should be an argument to the cstart, anyway.

As in, the `cstart` block should define the whole block shape? Since `celse` is its own block, I think the de-facto paradigm here is that parts of c-blocks are defined by their own blocks/lines.

> Any cend (either specified with :: or not), with cap, [bugs](http://scratchblocks.github.io/#if%20%3C%3E%20then%0A%0Aend%20%3A%3A%20cap%0A%0Afake%20C%20%3A%3A%20grey%20cstart%0A%20%20baz%20%3A%3A%20operators%0Aend%20%3A%3A%20cap%0A%0Atest%20%3A%3Acontrol%20cstart%0A%20%20say%20%5Bhello%5D%0Asee%20%5Basd%5D%20%3A%3Acelse%0A%20%20say%20%5Bit's%20me%5D%0Atesting%20%3C%3E%20%3A%3Acelse%0A%20%20say%20%5Bi%20was%20wondering%20if%20after%20all%20this%20years%20you'd%20like%20to%20meet%5D%0Aend%20%3A%3A%20cend%20cap%0A%0Athis%20should%20be%20outside%20%3A%3A%20cstart%0A%0A%3A%3A%20cend%20cap%0A%0Asay%20%5Bthere%20you%20are%5D). (It's better if you see it yourself, i'm not really sure how to explain it)

I think it's the "cap" shape taking precedence, which in this case means it's a cap-stack

**Comment by tjvr** [comment]
New plan: remove cstart and celse and cend; I've never liked them, and they're clearly too confusing.

You'll be able to create custom c blocks using the { } embedded script syntax.

**Comment by liam4** [comment]
Demo?

**Comment by Airhogs777** [comment]
The {} syntax can create c-blocks? I thought that was only for Snap! stuff. Will it allow the kind of fine control that cstart/else/end do (or at least probably should)?

**Comment by tjvr** [comment]
Example:
```
say ({})
say ({}▸)
say ({stamp}▸)
say ({stamp
move (10) steps}▸)
if <> then
else
end
switch (var) {
} case [foo] {
} case [bar] {
} :: control
```

**Comment by Airhogs777** [comment]
that's very cool, I approve

**Comment by liam4** [comment]
That's pretty cool! :tada:

![demo](https://cloud.githubusercontent.com/assets/9948030/14758586/99d0975a-08db-11e6-8b1f-6b8acec334af.png)

```
magic {
  it's magic :: grey
} magic2 {
  more magic :: operators
} end it :: cap control
```

I did notice that the branches/ends aren't quite tall enough, though..

**Comment by jupiterio** [comment]
This will break many scripts now :package: 

Still, i feel like it has more upsides than downsides

**Comment by Airhogs777** [comment]
> I did notice that the branches/ends aren't quite tall enough, though..

It's using the dimensions that Scratch uses to render blocks. For example, the word `else` looks right at this block height because it doesn't have a down-hanging letter like `g` or `y`, but words with those letters make it look too short.

**Comment by Jonathan50** [comment]
> Related.
> Any cend (either specified with :: or not), with cap, [bugs](http://scratchblocks.github.io/#if%20%3C%3E%20then%0A%0Aend%20%3A%3A%20cap%0A%0Afake%20C%20%3A%3A%20grey%20cstart%0A%20%20baz%20%3A%3A%20operators%0Aend%20%3A%3A%20cap%0A%0Atest%20%3A%3Acontrol%20cstart%0A%20%20say%20%5Bhello%5D%0Asee%20%5Basd%5D%20%3A%3Acelse%0A%20%20say%20%5Bit%27s%20me%5D%0Atesting%20%3C%3E%20%3A%3Acelse%0A%20%20say%20%5Bi%20was%20wondering%20if%20after%20all%20this%20years%20you%27d%20like%20to%20meet%5D%0Aend%20%3A%3A%20cend%20cap%0A%0Athis%20should%20be%20outside%20%3A%3A%20cstart%0A%0A%3A%3A%20cend%20cap%0A%0Asay%20%5Bthere%20you%20are%5D). (It's better if you see it yourself, i'm not really sure how to explain it)

Why is that song so popular? I've actually never heard it playing on the radio/TV/anything else... (Not that I listen to the radio much)

**Comment by jupiterio** [comment]
Probably because of the plain "Hello". How someone made a song based on one of the simplest words and one of the words that people first think of when asked: _Hello_ (But probably not say it because it's too dumb)
Just like Lionel Richie's Hello
_(Is it me you're looking for?)_

Also IMO the song is pretty nice.
