### ISSUE TITLE
Comment rendering glitches in Firefox/Edge

### ISSUE THREAD

**Issue by Choco31415** [tjvr/scratchblocks#142]
Comment rendering is a bit off in Firefox and Edge:

Firefox v.45.0.2
http://i.cubeupload.com/YFTN2C.png

Edge
http://i.cubeupload.com/dqBrSx.png

There are two interesting things to note. This bug seems to only occur on Windows. No Mac browsers, including Firefox v.45.0.2, are affected. On the PC, Chrome v.49.0.26 is unaffected.

Secondly, this bug occurs way more frequently on my test mediawiki than the Github testing page. In the affected browsers, approximately 95% of comments are affected. I checked with developer tools, and no styles are being forced on the scratchblock comments. Also, scrolling seems to make some comments re-render with new bugged colors.

I'm not sure, but I think that in image2 above, the half-yellow half-blue comment suggests something about why this bug is happening.

**Comment by tjvr** [comment]
Huh. I don't understand why this would happen. Can you give some idea of how to reproduce it?

**Comment by Choco31415** [comment]
On the github scratchblocks page, I copied the "move (10) steps // comment" block until I had 2-3 pages of the thing. I think it's important to had 2-3 pages instead of 1 page. Then, I scrolled through the script on the left and saw oddly rendered comments. Very occasionally, no comments would be bugged, at which point adding more blocks prompted some bugs to show again.

In the Mediawiki implementation, having any amount of blocks with comments caused the comments to render weirdly.

**Comment by Choco31415** [comment]
I've tested the scratchblocks plugin on a few other PC's, and have not been able to replicate this bug yet. This makes me assume that the bug is local to my PC, however I don't see what's special about it.

**Comment by arve0** [comment]
I can confirm the bug. Windows 10, Microsoft Edge.
![image](https://cloud.githubusercontent.com/assets/4810521/14760652/000ca04a-094a-11e6-88a2-060ae2deb98a.png)

**Comment by tjvr** [comment]
@arve0 Yes, that's a different glitch. One that I fixed recently; are you using the latest master?

**Comment by arve0** [comment]
No, I was not on latest master. Will check again.

**Comment by tjvr** [comment]
If anyone else can reproduce the issue in the OP, let me know.
