### ISSUE TITLE
Image replacements in wrong language

### ISSUE THREAD

**Issue by tjvr** [tjvr/scratchblocks#143]
If you select German, and write an image-replacement block in English, the icon does not appear.

http://scratchblocks.github.io/#?lang=de&script=when%20flag%20clicked%0A

**Comment by tjvr** [comment]
This doesn't work either:

http://scratchblocks.github.io/#?lang=de&script=Wenn%20%E2%9A%91%20angeklickt%0Adrehe%20dich%20%E2%86%BB%20um%20(9)%20Grad

**Comment by Airhogs777** [comment]
Same issue in translator, even before a second language is loaded: http://scratchblocks.github.io/translator/#when%20flag%20clicked

**Comment by tjvr** [comment]
Fixed.
