### ISSUE TITLE
Custom end blocks can't have text

### ISSUE THREAD

**Issue by tjvr** [tjvr/scratchblocks#147]
This is arguably not important.

**Comment by liam4** [comment]
> arguably

Okay.. *argues*

Please add this feature again..

**Comment by Airhogs777** [comment]
+1 for this option

**Comment by tjvr** [comment]
@liam4 the correct approach is to provide a use case :P

**Comment by Airhogs777** [comment]
The first thing that comes to mind is someone modding Scratch to add a do-while block

**Comment by Jonathan50** [comment]
The Scratch 2.0 alpha WHILE should have been called REPEAT WHILE, to match up with the other blocks \</completely-unrelated\>
