### ISSUE TITLE
allow existing c-blocks to use bracket notation

### ISSUE THREAD

**Issue by Airhogs777** [tjvr/scratchblocks#148]
It's inconsistent that existing c-blocks still use the `end` notation.

example: http://scratchblocks.github.io/#if%20%3C%3E%20then%20%7B%0A%7D%20else%20%7B%20%0A%7D%0A%0Aforever%20%7B%0A%7D

...these should be recognized and the `forever` block should have the `cap` shape and repeat-arrow applied

**Comment by tjvr** [comment]
I don't think this is important.
