### ISSUE TITLE
reporter and boolean-shaped "..." asymmetrical

### ISSUE THREAD

**Issue by Airhogs777** [tjvr/scratchblocks#149]
the ellipsis in `(...::)` and `<...>` is shifted slightly to the right. It might just be by a pixel or two but it stuck out to me.

[example](http://scratchblocks.github.io/#...%20%3A%3A%20hat%0A%3C...%3E%0A(...%3A%3A)%0A...)

**Comment by jupiterio** [comment]
I don't see it. It looks pretty normal for me.
http://i.cubeupload.com/rFaSzb.png

**Comment by Airhogs777** [comment]
Hm, it may be the font rendering on my computer. http://i.cubeupload.com/mc1m2F.png

**Comment by jupiterio** [comment]
I just checked by zooming in. Still normal. So, definitely the font rendering.

**Comment by tjvr** [comment]
There are supposed to be spaces anyway, oops.
