### ISSUE TITLE
Icon replacements don't always escape

### ISSUE THREAD

**Issue by Airhogs777** [tjvr/scratchblocks#154]
In the case of a non-aliased block, icon names are escaped correctly:
```
foo @greenFlag bar // icon appears
foo \@greenFlag bar // icon escapes correctly
```
but in the case of `when @greenFlag clicked`, all backslashes are ignored:
```
when \@gre\enF\lag clicked // still renders flag icon
```

**Comment by tjvr** [comment]
That is indeed a quirk of the implementation.

Does this matter?

**Comment by Airhogs777** [comment]
I can't imagine it'll cause anyone any problems, but I guess it's something to be aware of
