### ISSUE TITLE
"forever {}" has if/else shape

### ISSUE THREAD

**Issue by Airhogs777** [tjvr/scratchblocks#155]
`forever {}` is recognized as a `control cstart` but the brackets create another c-area, so you end up with two.
[example](http://scratchblocks.github.io/#forever%20%7B%7D%0Aend%0A%0Aforever%20%7B%0A%20foo%0A%7D%0A%20bar%0Aend)
I still think the best solution here would be to allow bracket notation in the place of end-notation, if that's technically feasible

**Comment by tjvr** [comment]
The new `{}` notation is explicitly designed to be for making custom things and hacks, so it's _deliberately_ experimental/unsupported behaviour and may change in future.

**Comment by Jonathan50** [comment]
What is it for? Can't what it's used for already be done with `:: cstart`, `:: celse`, `end` and `:: cend`? Is it documented somewhere?

**Comment by Jonathan50** [comment]
```
test { :: costumes
}
```
doesn't seem to work... :confused:

**Comment by Airhogs777** [comment]
> What is it for? Can't what it's used for already be done with `:: cstart`, `:: celse`, `end` and `:: cend`? Is it documented somewhere?

Iirc, `:: cstart`, `:: celse`, and `:: cend` no longer work -- this is their replacement. It also lets you create text in the "foot" of the c-block.

**Comment by Jonathan50** [comment]
Oh, right.
> It also lets you create text in the "foot" of the c-block.

That could already be done:
```
foo :: cstart
bar :: cend
```

**Comment by tjvr** [comment]
@Jonathan50 Relevant: #141
