### ISSUE TITLE
add block-shape classes to SVG

### ISSUE THREAD

**Issue by Airhogs777** [tjvr/scratchblocks#156]
It'll make the output easier to navigate programmatically if either the parent `g` tag or the block's background `path` has a class with its shape

I actually have a use case for this one: while writing [this](http://jsfiddle.net/Airhogs777/0ouwy7s8/embedded/result/) I had to resort to block color to identify the reporters

**Comment by tjvr** [comment]
I don't really understand why you'd want to navigate the output programmatically. This isn't really an intended use case.

**Comment by tjvr** [comment]
Sorry, I'm not going to do this. If it's super-important to you, maybe send a patch and I'll see what I think then. :)
