### ISSUE TITLE
Stack ring blocks don't render correctly anymore

### ISSUE THREAD

**Issue by jupiterio** [tjvr/scratchblocks#158]
Don't know if the syntax for them has changed, and haven't seen anything really that has mentioned it. Maybe it's the new custom C block syntax?

[Example](http://scratchblocks.github.io/#(%7Bsay%20%5Btest%5D%7D%20%E2%96%B8)%0A(%7Bsay%20%5Btest%5D%7D%20%40addInput))

**Comment by tjvr** [comment]
Poop.
