### ISSUE TITLE
Booleans with inputs don't work with the {} syntax

### ISSUE THREAD

**Issue by Jonathan50** [tjvr/scratchblocks#159]
```
if <foo> {
} else if <bar> {
} :: control
```
works fine, and
```
if ([a] = [b]) {
} else if ([c] = [d]) {
} :: control
```
works too, but
```
if <[a] = [b]> {
} else if <[c] = [d]> {
} :: control
```
messes stuff up.

It's probably a parser issue because
```
if ([a] = [b] :: boolean) {
} else if ([c] = [d] :: boolean) {
} :: control
```
works fine...

**Comment by tjvr** [comment]
Specifically, the hack we use for recognising `<>` as comparisons (and not syntax) is "is it between two inputs". Your problem here is that {} is an input!

**Comment by Jonathan50** [comment]
Oh.

**Comment by theonlygusti** [comment]
@tjvr That hack probably broke something else: https://github.com/tjvr/scratchblocks/issues/163

**Comment by Airhogs777** [comment]
I can't find a way to fix this with escaping alone, although the `([a] = [b] :: boolean)` workaround is a simple enough solution. Another option is for the bool-finding portion of the parser to ignore `{}` as inputs

**Comment by tjvr** [comment]
This one can also be solved using escaping, [for example](http://scratchblocks.github.io/#if%20%3C%5Ba%5D%20%3D%20%5Bb%5D%3E%5C%20%7B%0A%7D%20else%20if%20%3C%5Bc%5D%20%3D%20%5Bd%5D%3E%5C%20%7B%0A%7D%20%3A%3A%20control).

**Comment by Airhogs777** [comment]
Wait, so a backslash before a > escapes it and a backslash after ensures that it's parse as a bracket? cool! :D

**Comment by tjvr** [comment]
Specifically backslashes can escape spaces, which means the input-detection can't "see" the input

**Comment by Jonathan50** [comment]
Oh, like
```
\ \ \ \ \ \ \ \ block with a lot of padding\ \ \ \ \ \ \ \ \ \ \ :: grey
```
But why doesn't [this](http://scratchblocks.github.io/#%5C%20%5C%20%5C%20%5C%20%5C%20%5C%20%5C%20%5C%20block%20with%20a%20lot%20of%20padding%5C%20%5C%20%5C%20%5C%20%5C%20%5C%20%5C%20%5C%20%5C%20%5C%20%5C%20%3A%3A%20grey) work? Putting a space before the 'b' seems to fix it.
