### ISSUE TITLE
Check backpack plugin works for cloud variables

### ISSUE THREAD

**Issue by tjvr** [tjvr/scratchblocks#162]
It probably doesn't.

**Comment by Jonathan50** [comment]
There is a backpack plugin? What is a plugin?

**Comment by tjvr** [comment]
@Jonathan50 https://github.com/tjvr/scratchblocks/issues/121

**Comment by tjvr** [comment]
So I think it turns out that it doesn't work, *and* it's something we can't fix, because backpack scripts can't specify whether their variables are cloud or not. But I might be misremembering.

Anyone want to look into this?
