### ISSUE TITLE
Parsing fails on lots of angle-brackets

### ISSUE THREAD

**Issue by theonlygusti** [tjvr/scratchblocks#163]
See this post on the forums: https://scratch.mit.edu/discuss/topic/195968/?page=5#post-1955054

It used this code:

    <<(a) = <(b) < (b)>> < (b)>

Which should have produced ![http://i.cubeupload.com/bAZO2e.png](http://i.cubeupload.com/bAZO2e.png) but actually produced ![http://i.cubeupload.com/7mtpKt.png](http://i.cubeupload.com/7mtpKt.png)

This is still a problem in the latest version: [see here](http://scratchblocks.github.io/#%3C%3C(a)%20%3D%20%3C(b)%20%3C%20(b)%3E%3E%20%3C%20(b)%3E)

**Comment by theonlygusti** [comment]
Might not be the parsing which is failing, but something definitely is 😝

**Comment by tjvr** [comment]
It's a parser quirk, yes. I'd hesitate to call it a bug, since this will happen only very rarely in real Scratch code (if it's possibly at all!).

The way the scratchblocks parser has worked since v2 is to treat gt/lt symbols as labels iff they occur between inputs; otherwise they are parsed as syntax.

**Comment by Airhogs777** [comment]
Also, this code can be achieved with escaping: `<<(a) = <(b) < (b)>> \< (b)>` ([link](http://scratchblocks.github.io/#%3C%3C(a)%20%3D%20%3C(b)%20%3C%20(b)%3E%3E%20%5C%3C%20(b)%3E))

**Comment by theonlygusti** [comment]
@tjvr This is possible in Scratch (hence the screenshot) but if @Airhogs777 's workaround will work in v3 then it seems it will be okay.

**Comment by tjvr** [comment]
Solved using escaping.

**Comment by Airhogs777** [comment]
One real-life situation where this might happen is when someone compares booleans by casting them to numbers (not sure why you would but you could).

Does the generator accommodate for this kind of situation?

**Comment by theonlygusti** [comment]
@Airhogs777 That is exactly the reason that I needed to do this.
