### ISSUE TITLE
This isn't an issue...

### ISSUE THREAD

**Issue by banana439monkey** [tjvr/scratchblocks#164]
How do I use this plugin on http://askawayteamforums.boards.net

**Comment by liam4** [comment]
Depends on if that forum supports scratchblocks or not.

**Comment by banana439monkey** [comment]
it uses proboards

**Comment by liam4** [comment]
I don't think there's a scratchblocks plugin for proboards. I have no idea how different it is from other forum (or similar) software but perhaps looking at [wiki-scratchblocks](https://github.com/tjvr/wiki-scratchblocks) might help you make your own plugin?

**Comment by banana439monkey** [comment]
I actually want to use the scratchblocks plugin. :P

On 5 May 2016 at 11:16, Liam <notifications@github.com> wrote:

> I don't think there's a scratchblocks plugin for proboards. I have no idea
> how different it is from other forum (or similar) software but perhaps
> looking at wiki-scratchblocks <https://github.com/tjvr/wiki-scratchblocks>
> might help you make your own plugin?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/tjvr/scratchblocks/issues/164#issuecomment-217118567>
>



-- 
*Got a problem or a question? Help? Ask away and I'll help! It's not like I
won't. <https://scratch.mit.edu/users/banana439monkey>*

**Comment by banana439monkey** [comment]
btw, what language is the sb plugin made in?

**Comment by liam4** [comment]
Looks like PHP?

**Comment by Choco31415** [comment]
Actually, it's javascript with a touch of PHP.

Anyway, if you want to add this to your website, you'll first need to include a JS library. Then you'll need to parse the page for <scratchblocks> tags and replace those with <pre class="blocks"></pre>. Finally, you'll need to run this JS command: scratchblocks.renderMatching("code.blocks", {languages: ["en"]});

**Comment by banana439monkey** [comment]
Ah. :/ Any way I can download the whole website, like mediawiki?
http://askawayteamforums.boards.net/

On 5 May 2016 at 21:39, Choco31415 <notifications@github.com> wrote:

> Actually, it's javascript with a touch of PHP.
>
> Anyway, if you want to add this to your website, you'll first need to
> include a JS library. Then you'll need to parse the page for tags and
> replace those with
>
> . Finally, you'll need to run this JS command:
> scratchblocks.renderMatching("code.blocks", {languages: ["en"]});
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/tjvr/scratchblocks/issues/164#issuecomment-217271694>
>



-- 
*Got a problem or a question? Help? Ask away and I'll help! It's not like I
won't. <https://scratch.mit.edu/users/banana439monkey>*
