### ISSUE TITLE
Bug: Parameter names not displaying in the generator

### ISSUE THREAD

**Issue by MegaCode18** [tjvr/scratchblocks#165]
Whenever I import a custom block, the parameter name is always `r`. This (I think) is due to the fact that you read the wrong value in the JSON: You are reading `["getParam", <parameter name>, "r"][2]`, instead of `["getParam", <parameter name>, "r"][1]`. For example, the Leafino text engine looks like this:

![Scratcblocks code uses 'r' for parameters, instead of parameter name](http://u.cubeupload.com/_CodeLyoko/scratchblocks.png)

**Comment by tjvr** [comment]
I'd actually fixed this in master, but not updated the website. Fixed, thanks!
