### ISSUE TITLE
Add @cloud for ☁

### ISSUE THREAD

**Issue by tjvr** [tjvr/scratchblocks#169]
@hardmath123 wins.

**Comment by Hardmath123** [comment]
Yaaaaay! What prompted this? :-)

**Comment by tjvr** [comment]
Well, you were arguing for this the other day :P

Want to implement it for me? xD

**Comment by jupiterio** [comment]
\:D/

**Comment by Airhogs777** [comment]
Has nobody volunteered for this yet? I guess I can do it
