### ISSUE TITLE
Angled Booleans

### ISSUE THREAD

**Issue by tjvr** [tjvr/scratchblocks#17]
Boolean blocks are currently rounded (border-radius) as the CSS for triangular ends is tricky. [example](http://blob8108.github.io/scratchblocks2/#if%20%28mouse%20down%3F%29)

[joooni](http://scratch.mit.edu/users/blob8108/#comments-33977) has a [working example](http://jms-web.tk/Blocksplugin%202.0/anothertest.htm) using images and JS. The JS is doable, but I don't want to use images as I'd need 14 colour variations...

**Comment by Airhogs777** [comment]
I threw something together: http://jsfiddle.net/Airhogs777/4tan9wmL/

**Comment by blob8108** [comment]
Nice! That's pretty similar to what I came up with. But it has problems like needing to set height, as you've pointed out in your description.

**Comment by Airhogs777** [comment]
Actually, setting height was the easy part. (I tried to explain this in the fiddle) I set min-width and min-height to the value I wanted and had the pseudo-elements inherit that. The part I've been struggling with is moving the triangles left and right so they line up with the edge of the block

**Comment by tjvr** [comment]
Fixed via #94 :D
