### ISSUE TITLE
Rename "scratchblocks"

### ISSUE THREAD

**Issue by tjvr** [tjvr/scratchblocks#170]
Following the announcement of [Scratch 3.0](https://scratch.mit.edu/discuss/topic/199904/?page=1) and [Scratch Blocks](https://github.com/llk/scratch-blocks), now might be a good moment to rename the (IMHO already confusing) `scratchblocks` project.

Any suggestions?

**Comment by liam4** [comment]
`scratchblocksthatarerenderedusingtextastheinput`?

**Comment by jupiterio** [comment]
scratch4forums maybe? :)

**Comment by Airhogs777** [comment]
Scrender, SVGratch (or Gratch for short). never mind, I don't like any of those... how about BlockTalk?

**Comment by tjvr** [comment]
My best thought was "blockpix".

**Comment by jupiterio** [comment]
I tried to avoid "block" as it's too general, and scratchblocks is for scratch blocks

And honestly, mine's pretty boring :package:

**Comment by tjvr** [comment]
<img width="588" alt="screen shot 2016-06-01 at 09 03 35" src="https://cloud.githubusercontent.com/assets/639289/15702413/d7497726-27d7-11e6-970a-691172da9377.png">

**Comment by tjvr** [comment]
@arve0 Do you disagree? :)

**Comment by arve0** [comment]
Yes, I do not think changing the name will gain much. The name is established and well known by those who use this software. 

Why do you think the name is confusing (I'm not a native english speaker)?

**Comment by tjvr** [comment]
@arve0 The main reason would be to avoid confusion with "Scratch Blocks", a project just announced by MIT which will be part of Scratch 3.0.

But the name is well-established, as you say. Hmm.

**Comment by arve0** [comment]
Aha, I see. Here is some context to how easy it is to find scratchblocks:

https://google.com/?q=scratchblocks
https://google.com/?q=scratch-blocks
https://google.com/?q=scratch%20blocks

**Comment by tjvr** [comment]
New plan: add a link to Scratch Blocks to the top of the readme, Wikipedia-disambiguation style.

**Comment by Airhogs777** [comment]
You could open an issue over there asking them to do the same

**Comment by tjvr** [comment]
@Airhogs777 Nah. I expect the next version of `scratchblocks` will be based on `Scratch Blocks` itself, so, it would be a brand new project anyway.
