### ISSUE TITLE
Translated number dropdown text is invisible

### ISSUE THREAD

**Issue by bleush38p** [tjvr/scratchblocks#172]
In the translator (on the translated side only), literal number dropdown text has the class `literal-number-dropdown` and not `sb-literal-number-dropdown`, so it does not have the black fill, making it invisible in its white container.

This only happens for blocks that have been translated, not any custom blocks. [(example)](http://scratchblocks.github.io/translator/#?lang=es&script=delete%20(all%20v)%20of%20%5Blist%20v%5D%0Apoint%20in%20direction%20(90%20v)%0Afoo%20(thing%20v)%20%3A%3A%20%2389b) (additionally, the custom color bit `:: #89b` doesn't show up in the translated code, but is still correct in the scratchblocks)

![image](https://cloud.githubusercontent.com/assets/7422958/15485929/e7cce230-2107-11e6-9275-6b97f28a8d55.png)

**Comment by tjvr** [comment]
Thanks for reporting! Want to send a patch? :-)

**Comment by tjvr** [comment]
> the custom color bit :: #89b doesn't show up in the translated code, but is still correct in the scratchblocks

Ooh, interesting. I could probably make an argument that this is deliberate; if it bothers you, open another issue/send a patch. Thanks!
