### ISSUE TITLE
Exported SVG has broken styles

### ISSUE THREAD

**Issue by exo7math** [tjvr/scratchblocks#175]
Dear tjvr,

thank you for your fantastic generator of image of blocks!

I have trouble with the svg files. The image is not well pictured on the screen (see the picture). I can fix part of the problem, playing with Inkscape parameters, but still I will have trouble to import it in Libre Office (because the fonts are not the same and then texts go out of the blocks).

![svg-scratchblocks](https://cloud.githubusercontent.com/assets/16621073/16015998/c0ef593a-3198-11e6-90d2-64eeedca0349.png)

Finally it would be nice to have a png image of better resolution (say 300 pp) for printing !

Thanks again,
Arnaud

PS: I'm on Ubuntu 16.04, using Firefox or Chromium

**Comment by tjvr** [comment]
What are you viewing the SVGs in? Are there easy fixes we can make to scratchblocks to make that renderer happy?

**Comment by exo7math** [comment]
The rendering has the same problem with the standard picture viewer of Ubuntu, with Inkscape and Gimp. But the rendering is good when the files is opened with Firefox and Chromium. 

With Inkscape I can show the blocks correctly by changing the filling of the background (clicking the question mark "undefined filling", see picture), but the save file is still bad!
![inkscape](https://cloud.githubusercontent.com/assets/16621073/16018156/80fc21d6-31a3-11e6-9303-931eae261947.png)


My files does not pass this validator test: https://validator.w3.org/ Is this normal?

**Comment by tjvr** [comment]
Fixed, thanks!
