### ISSUE TITLE
Rendering without DOM

### ISSUE THREAD

**Issue by arve0** [tjvr/scratchblocks#182]
I've [hacked a bit](https://github.com/arve0/scratchblocks/commits/node) trying to avoid the dependency to the DOM, making server side rendering possible without a browser.

Seems like this is almost possible, except for the size measuring `getBBox` of text. Have you looked into [node-canvas](https://github.com/Automattic/node-canvas) any?

Any ideas?

Edited: getBBox is SVG, not canvas.

**Comment by arve0** [comment]
Got this rendered using node-canvas to measure string lengths:

![skjermbilde 2016-07-08 kl 01 46 13](https://cloud.githubusercontent.com/assets/4810521/16673399/18de5358-44ae-11e6-9d2a-3c8a72bcf360.png)

Though, trouble with font size, as correct font is not available for cairo (ref https://github.com/Automattic/node-canvas/pull/715).

See [branch node on my fork](https://github.com/arve0/scratchblocks/tree/node) (code is a mess right now, will clean up if I can get it to work).

**Comment by tjvr** [comment]
I've thought about server-side rendering, but I rejected it as an official idea (I don't want to end up hosting an SVG/PNG-rendering service!). scratchblocks quite deliberately renders things on the client.

The easiest thing is just to use PhantomJS; then you can render to SVG/PNG/whatever you want, with minimal extra effort. Note that if you render to SVG, the metrics will be wrong if the user doesn't have the font you rendered the SVG with! (another argument in favour of client-side rendering).

So I don't have any useful suggestions, sorry. But if you're interested in finishing this (as a node module?) then I'd be very happy to merge it to master :)

**Comment by arve0** [comment]
> Note that if you render to SVG, the metrics will be wrong if the user doesn't have the font you rendered the SVG with! (another argument in favour of client-side rendering).

You are correct. If I understand correctly, `Lucida Grande` is the official font for keywords and `Helvetica` for comments?

Not sure if those fonts are free to distribute, but one could provide web font for those who miss these fonts. Web fonts should be [supported](http://caniuse.com/#feat=fontface) in all browsers.

**Comment by arve0** [comment]
> But if you're interested in finishing this (as a node module?)

Yes, I will finish it. I'll try to think about how it can coexist with the client code. Might add a build step with node, if that is alright?

**Comment by tjvr** [comment]
> Might add a build for browsers with node/npm, if that is alright?

I'm not quite sure what you mean by this, but I'm sure that's fine. :)

**Comment by arve0** [comment]
It essentially means that you do a build step for the browser release. E.g.

```
make browser-build
```

where the equivalent in npm-land would be

```
npm run browser-build
```

Anyhow, I'm currently doing some heavy refactors, to get rid of the python dependency. This might not fall to your taste. I'll give a heads up when I have it fully working.

**Comment by tjvr** [comment]
> This might not fall to your taste

Presumably you're talking about the `build_translations.py` script? I've been thinking about converting that to Node myself, but I just don't have the time. If it still works the same I'd be very happy with that :)

**Comment by arve0** [comment]
> Presumably you're talking about the build_translations.py script?

Yes, I'm porting `build_translations.py` to node now.
