### ISSUE TITLE
Importing scripts to backpack puts scripts at the end of the backpack, not the start

### ISSUE THREAD

**Issue by liam4** [tjvr/scratchblocks#184]
![Picture](https://cloud.githubusercontent.com/assets/9948030/16697176/d1365d40-451e-11e6-8fc6-3df43a705b1c.png)

On the far right are the newly imported using scratchblocks scripts. Everything else is from, like, 2013.

**Comment by tjvr** [comment]
Yes that's what I thought too! @hardmath123

**Comment by CosmicWebServices** [comment]
yeah I noticed this

**Comment by joker314** [comment]
Looks like an easy fix, you use `.push()` when you should use `.unshift()`. I couldn't find the code and therefore couldn't make a PR, but the correction should be made on line 46 of backpck.js The amended line should look like this: `parsed.unshift(obj);`
Good luck!

**Comment by tjvr** [comment]
Duplicate of #161.
