### ISSUE TITLE
Recognise based on shape too

### ISSUE THREAD

**Issue by tjvr** [tjvr/scratchblocks#185]
[This sort of thing](http://scratchblocks.github.io/#say%20(when%20flag%20clicked)%0Aturn%20cw%20%3Cdistance%20to%20%5Bsprite%20v%5D%3E%20degrees%0Amove%20(stamp)%20steps%0Aif%20(mouse%20down%3F)%20then) just shouldn't be allowed.

![scratchblocks](https://cloud.githubusercontent.com/assets/639289/16811095/b39e4b86-491e-11e6-9bde-16e3d2a2e587.png)

This is relevant to the backpack feature -- it's the most obvious way to create invalid scripts. These blocks are recognised based on their text, and so they have `selector`s, so can be converted to JSON. This is undesirable.

I'm also going to modify the parser to look for whitespace after `{}`, to decide whether to parse as a Block or a Script.

**Comment by joker314** [comment]
Would you prefer the scripts you showed to be not backpack-able? What about scripts like this, where everything is the correct shape, but is still cannot be recreated in the editor:
`<key (variable) pressed>`? Would you allow this or also try to prevent it?

**Comment by joker314** [comment]
Wait, I would like the blocks to produce the opcodes based on their text, but add to the backpack the blocks with the correct shapes. Would that be acceptable. I think it should allow stack blocks as inputs to blocks, as this new system makes block hacking easier, and while it is true that block hacking is against the Terms of Use, I don't see this kind of block hacking harmful. I do understand that this could be considered sub-optimal, but many Scratchers would prefer this. It rather depends on what the Scratch Team says, whether they deem this type of block hacking bad. My opinion on this is that it should be allowed, but I know that some will disagree

**Comment by joker314** [comment]
After the user @herohamp created a mock-up, it works as I prefer, the text i forced into its correct shape, but still allowed, and I really like this. It is currently optimal for safe block hacking, and while this may be against the terms of use, if the JSON is valid enough to produce some kind of script in the editor, I think it should be allowed. Please, keep it the way it is, because a bit of block hacking can make more efficient programming, something Scratch should teach. Have a nice day everybody :)

**Comment by joker314** [comment]
On the other hand this might be a good idea, as long as you are alright with `key var pressed` type hacking. I am going to (also) give you a thumbs up

**Comment by bobbybee** [comment]
There are some legitimate uses of this, such as a pop reporter.

**Comment by tjvr** [comment]
* Also modify the parser to look for whitespace after `{}`, to decide whether to parse as a Block or a Script.

**Comment by herohamp** [comment]
Sorry to come if this is not my conversation but I got a notification about it. I think it is cool how we can make our "Custom" blocks
