### ISSUE TITLE
Backpack plugin improvements.

### ISSUE THREAD

**Issue by tjvr** [tjvr/scratchblocks#190]
- [ ] Restrict invalid block JSON. I think the ST might be thinking about removing the "Add to Backpack" feature... they're not a fan of the fact you can create "hacked" blocks. This needs to be more restricted.
- [ ] Add to beginning, not the end, as per #161.
- [ ] Make the button smaller and less annoying.
- [ ] Revisit the "at least one block" check; for one thing, this doesn't make sense if you added a C block.

**Comment by liam4** [comment]
> they're not a fan of the fact you can create "hacked" blocks.

@(scratch team) Please can we just make them not hacked blocks? Is that that hard?

> Make the button smaller and less annoying.

Maybe a backpack icon? (With the current text as alt)

**Comment by tjvr** [comment]
> not hacked blocks

It's not clear what you're asking for here.

**Comment by liam4** [comment]
e.g. dropping inputs into most prevented input slots, like set *name* or *attribute* of sprite.

**Comment by tjvr** [comment]
> I think the ST might be thinking about removing the "Add to Backpack" feature... they're not a fan of the fact you can create "hacked" blocks

As it turns out, they have removed it. :-(
