### ISSUE TITLE
`:: stack ring`'s input literals looks weird

### ISSUE THREAD

**Issue by liam4** [tjvr/scratchblocks#193]
I imagine the right thing to do would be to render it as if it was just a `:: ring` (no `:: stack`).

![Example (zoomed in)](https://cloud.githubusercontent.com/assets/9948030/17464036/255fbf62-5cab-11e6-93ed-1036a07501cb.png)

[Link.](http://scratchblocks.github.io/#%28%5Bthis%20makes%20no%20sense%20v%5D%20%3A%3A%20%23CCC%20stack%20ring%29%0A)

Found this in [udoxas's signature](https://scratch.mit.edu/discuss/post/2138237/).

**Comment by tjvr** [comment]
The word `stack` is irrelevant here.

The actual issue is that any input inside a ring apparently has a stack-shaped shadow around it. But since that's invalid anyway, I doubt it's worth fixing.
