### ISSUE TITLE
Inline Nested Blocks

### ISSUE THREAD

**Issue by carlflor** [tjvr/scratchblocks#194]
Hi, is there a way I could show a move block within repeat block inline? Thanks!

**Comment by tjvr** [comment]
I'm sorry, I don't understand the question. Could you explain it a bit more? :)

**Comment by carlflor** [comment]
hi! apologies for the late feedback.

For example, I wanna show 
![scratchblocks](https://cloud.githubusercontent.com/assets/4861092/17957668/0d91d388-6ac6-11e6-9062-daf97dbf9de3.png)

How do I write it in html? This doesn't seem to work
`<code>repeat ( 10) move (10) steps</code>`

**Comment by tjvr** [comment]
You want something like this:

```html
<pre>
repeat (10)
  move (10) steps
end
</pre>
```

and then
```html
<script src="https://scratchblocks.github.io/js/scratchblocks-3.x-min.js"></script>
<script>
scratchblocks.renderMatching('pre.blocks');
</script>
```
