### ISSUE TITLE
[Minor] The Dutch <<> of <>> Block Appears as a Sensing Block

### ISSUE THREAD

**Issue by Choco31415** [tjvr/scratchblocks#198]
Here's a screenshot, with the scratchblocks code on the left, and an image of what the of block should look like in the right:

http://u.cubeupload.com/Choco31415/ScreenShot20160823at.png

The two blocks should not be mixed up because one uses drop down menus, while the other uses booleans.

**Comment by tjvr** [comment]
This is expected behaviour. scratchblocks can only tell apart the blocks if the first input is a dropdown; it tests them against the list 'sin', 'cos', 'abs'...

**Comment by liam4** [comment]
FYI there's a workaround - just attach `:: operators` to the `of` block:

```
<<(1) = (1)> of <(1) = (2)> :: operators>
```

![scratchblocks](https://cloud.githubusercontent.com/assets/9948030/17930224/81ff70fe-69db-11e6-8835-055113d1a756.png)

I'm just confused, though.. I can't reproduce the OP's issue:

![can't reproduce image](https://cloud.githubusercontent.com/assets/9948030/17930298/de4e8f8e-69db-11e6-8622-142072ce6c5c.png)

Shouldn't that be blue/sensing?

**Comment by Choco31415** [comment]
@liam4:
The bug is not for German. It's for Dutch (nl).

@tjvr:
Oh, you are correct. It would be nice if there was a way to differentiate between the two blocks...

**Comment by tjvr** [comment]
FWIW, there's a similar problem with the "set pen color to" block; this is why tosh renames it "set pen hue to".

**Comment by liam4** [comment]
>  The bug is not for German. It's for Dutch (nl).

@Choco31415 Oh, hahaha, I missed that.. forgive me :P
