### ISSUE TITLE
Command line

### ISSUE THREAD

**Issue by exo7math** [tjvr/scratchblocks#199]
Dear scratchblokers,

is there a way to use scratchblock in a command line interface? I would like to transform a text file containing Scratch instructions into on image with a command looking like:
   `scratchblocks myfile.txt myimage.svg`

Is it possible ? 

Then, since I have troubles with the svg image (see #175, #178) to be included in a LaTeX file, I can transform it as a png image of high resolution using [svgexport](https://github.com/shakiba/svgexport).

It would enable some automatic treatment, keeping only a text file as source.

Best,
Arnaud

**Comment by arve0** [comment]
This is already available, but you need to write a litte js to make it work. See [tests/test.js](https://github.com/tjvr/scratchblocks/blob/master/tests/test.js).

**Comment by exo7math** [comment]
Thanks for the answer, but could you please give more details for the installation and the commands?
Arnaud

**Comment by Airhogs777** [comment]
> Dear scratchblokers,
scratchblokes

**Comment by exo7math** [comment]
Sorry, but I do not know how to do it. I've installed Node.js, download the git repository 'scratchblocks', I can run `js test.js` but what to do next ?

**Comment by arve0** [comment]
> I can run `js test.js` but what to do next ?

You mean `node tests/test.js`? That will render all `.txt` in the test folder to SVG.

What you will need to do, to solve your specific problem:

1. Install [nodejs](https://nodejs.org).
2. Open a terminal. (Commands below will depend on your operating system).
3. `mkdir a_folder`
4. `cd a_folder`
5. `npm install tjvr/scratchblocks`
6. Create a file called `generate_svgs.js` with this contents (equivalent to test.js):

  ```js
var fs = require('fs');
var scratchblocks = require('scratchblocks');

fs.readdirSync(__dirname)
  .filter(file => file.match(/\.txt$/))
  .map(file => __dirname + '/' + file)
  .map(file => ({ filename: file, content: fs.readFileSync(file, 'utf8') }))
  .map(test => Object.assign(test, {
    svg: scratchblocks(test.content, { languages: ['en', 'de'] })
  }))
  .map(test => {
    var out = test.filename.replace('.txt', '.svg');
    fs.writeFileSync(out, test.svg);
  });
  ```
7. Create a `.txt` file with scratch code.
8. Run `generate_svgs.js` with `node generate_svgs.js`.

**Note:** The rendered SVGs will most likely look OK on same operating systems (e.g. windows -> windows), but may not on other operating system due to different fonts (e.g. windows -> mac).

**Comment by exo7math** [comment]
Dear arve0, thanks a lot for the answer. It works exactly as you said. Is it possible to transform the files not of the current directory but of another (changing) directory? It would be nice if it can be executed as a purely command line (exactly as the [ svgexport](https://github.com/shakiba/svgexport) package).

Secondly it seems that the fonts are depending heavily on the os. 
The first image is generated locall, the second by http://scratchblocks.github.io (then convert to png by svgexport). Any idea?


![bloc-home](https://cloud.githubusercontent.com/assets/16621073/18255267/42897efc-73a8-11e6-9c85-a605117b1397.png)


![bloc-server](https://cloud.githubusercontent.com/assets/16621073/18255276/5564fcae-73a8-11e6-9918-bf5cf9bd2c62.png)

**Comment by arve0** [comment]
> Is it possible to transform the files not of the current directory but of another (changing) directory?

Yes. That is `__dirname` in the line

```
fs.readdirSync(__dirname)
```

You may swap `__dirname` with [`process.argv[2]`](https://nodejs.org/docs/latest/api/process.html#process_process_argv) for specifying folder through terminal. If you want finer control, [commander](https://www.npmjs.com/package/commander) might help you out.

> Secondly it seems that the fonts are depending heavily on the os. 
The first image is generated locall, the second by http://scratchblocks.github.io (then convert to png by svgexport). Any idea?

If one could find a font which are available and equal on all systems... Currently fonts are defined [here for labels](https://github.com/tjvr/scratchblocks/blob/master/src/style.css#L2) and [here for comments](https://github.com/tjvr/scratchblocks/blob/master/src/style.css#L70). [fontfamily.io](http://fontfamily.io/Lucida_Grande,Lucida_Sans_Unicode,Verdana,Arial,sans-serif;) will help you translate what this means for different operating systems.

**Comment by exo7math** [comment]
Ok thanks! I close the ticket.

**Comment by tjvr** [comment]
> If one could find a font which are available and equal on all systems... Currently fonts are defined here for labels and here for comments. fontfamily.io will help you translate what this means for different operating systems.

This is quite sad, isn't it? I believe I'm using the same fonts as the Scratch flash player does. Is it worth us raising another ticket to improve this? :)
