### ISSUE TITLE
Apostrophe (in french)

### ISSUE THREAD

**Issue by exo7math** [tjvr/scratchblocks#204]
It seems that there is one non standard apostrophe used to define blocks in french. 
You should write "répéter jusqu’à" (repeat) instead of "répéter jusqu'à". It is quite subtle, but the first apostrophe is not available on french keyboard (you have to translate the blocks from english to french to get the correct syntax!)
![apostrophe_in_french](https://cloud.githubusercontent.com/assets/16621073/18806452/22db6f78-822d-11e6-93c7-e566d707c0e8.png)
This is certainly not a major bug!!

Thanks again for your program, which is fantastic to write activities for kids in Scratch.

**Comment by tjvr** [comment]
> Thanks again for your program, which is fantastic to write activities for kids in Scratch

Thanks! :-)

Is this a curly quotes vs. straight quotes issue? It's (presumably) a bug in the original translation files. Probably worth us adding a patch to minify_hash() so you can use either.

**Comment by tjvr** [comment]
I wrote a patch for this. Are you able to test it? :)

**Comment by exo7math** [comment]
Sorry, I can't test it. I only use online version.
