### ISSUE TITLE
"loud?" block appearing as obsolete (red)

### ISSUE THREAD

**Issue by PullJosh** [tjvr/scratchblocks#205]
This [should be](https://wiki.scratch.mit.edu/wiki/Loud) a sensing block.

![image](https://cloud.githubusercontent.com/assets/5458180/18820946/d91e18f6-836f-11e6-84d5-1940bf14375d.png)

**Comment by tjvr** [comment]
Nah—we show removed blocks (like "if <>"!) as obsolete. :-)
