### ISSUE TITLE
Custom blocks don't get rendered correctly

### ISSUE THREAD

**Issue by peeratham** [tjvr/scratchblocks#210]
Seems like custom blocks didn't get rendered correctly:

<[3]<[4]>
jump (1) ["jumping"] <[3]<[4]>
jump (1) ["jumping"] <mouse down?>

define jump (height)  [message] <bool?>

![scratchblocks](https://cloud.githubusercontent.com/assets/3270967/22786418/6f2d1bb6-eea6-11e6-9069-035669a9d157.png)

**Comment by tjvr** [comment]
Try backslash-escaping the `<`.

```
jump (1) ["jumping"] <[3] \< [4]>
```

**Comment by peeratham** [comment]
Thank you for the hint!  It works with some tweaks:
<[3]<[4]>
jump (1) ["jumping"] <[3] \< [4]>   //not this one
jump (1) ["jumping"] \ <[3] < [4]>  //this one works!

define jump (height)  [message] <bool?>
![scratchblocks 2](https://cloud.githubusercontent.com/assets/3270967/22786897/52124c16-eea8-11e6-87bf-894d040f731c.png)
