### ISSUE TITLE
Variable and parameter rendering inside custom block definition

### ISSUE THREAD

**Issue by peeratham** [tjvr/scratchblocks#211]
I hope there is a way to differentiate between a variable and a parameter when rendering inside custom block definition:

```
say (number1)
define jump [number1]
say (number1) for (2) secs
say (‌‌ number1) for (2) secs  // inserted an invisible character before number1 so it's not rendered as a parameter
```
![scratchblocks 1](https://cloud.githubusercontent.com/assets/3270967/22863606/50cfd362-f111-11e6-92bf-34bd9dea15c3.png)

**Comment by tjvr** [comment]
There is!
```
(foo::custom-arg)
(foo::variables)
```

**Comment by peeratham** [comment]
Thank you!
