### ISSUE TITLE
Translate scratchblocks generator

### ISSUE THREAD

**Issue by pseudobjorn** [tjvr/scratchblocks#33]
It would be very useful if the online tool at http://blob8108.github.io/scratchblocks2/generator/ was updated to include a language-dropdown similar to what is used by the tool at http://blob8108.github.io/scratchblocks2/. This would reduce the amount of work required by the translators when they are writing Scratchblocks for the Scratch curriculum.

**Comment by tjvr** [comment]
Done! See <http://scratchblocks.github.io/generator/>
