### ISSUE TITLE
Boolean insert ring in custom-arg appears as red instead of purple

### ISSUE THREAD

**Issue by DevanWolf** [tjvr/scratchblocks#40]
The outlines of an empty boolean insert of a custom-arg block appear red as obsolete instead of actual pruple. [Example](http://scratchblocks.github.io#report%3C%3E::custom-arg)

As a result, it looks unrealistic! Please fix this!

**Comment by tjvr** [comment]
> Hmm... It looks like you havn't fixed this problem I mentioned here a long time ago, please do it quickly, please.

Please use a calmer tone, and [read the contributing docs](https://github.com/tjvr/scratchblocks/blob/master/.github/CONTRIBUTING.md). I have no obligation to fix bugs in my code for you...
