### ISSUE TITLE
npm package

### ISSUE THREAD

**Issue by arve0** [tjvr/scratchblocks#49]
Hi!
It would be lovely if this package was published to npm or bower. I and @kwrl are writing a lesson builder, and would very much like to have dependencies taken care of by npm.

If you're not interested in coding this, will you mind a PR and pubilsh it?

**Comment by andylolz** [comment]
> but this is not immediately obvious

I just realised this is in fact clearly documented! Serves me right for not reading the dev-readme :)

**Comment by blob8108** [comment]
Hmm, I should probably link dev-readme from the main readme somewhere. (I thought I had.)

**Comment by seriema** [comment]
@tjvr where are you on this? Do you want a PR? It's pretty quick otherwise and we could just to a Skype call or something and I'll walk you through it.

**Comment by tjvr** [comment]
If someone wants an npm package for a demonstrably useful reason such as it simplifies their deployment (and not "it's prettier this way"), they can send me a PR. :-)

**Comment by seriema** [comment]
It would allow scratchblocks to become part of tools or other projects much easier. Some use `npm` to easily get front end libraries while some prefer [Bower](http://bower.io) and that's awesome for certain projects. Personally I want to plug it into [my current tool chain](https://github.com/kodcentrumcollaborative/Kodstuga_HT15/commit/146d7126c046c0209433718e0ee31ab42c0d4c2f?diff=unified) (click "changed files" to get an overview). We at Kodcentrum (Swedish version of Code Club I guess) just started converting our Word docs of exercises to markdown. With Gulp I'm able to generate HTML so we can print them easier. This is thanks to someone that wrote the [Marked](https://www.npmjs.com/package/marked) node module, which someone then wrapped into a [Gulp plugin](https://www.npmjs.com/package/gulp-markdown). If scratchblocks was easily used as a node module then I'd be able to do create the same kind of things and I'm sure other uses for it would show up. Writing markdown + scratchblocks feels like a great thing as well!

**Comment by tjvr** [comment]
Don't the Code Club people already have tooling for writing markdown + scratchblocks with pandoc? You could just use that...

**Comment by seriema** [comment]
They have a fork of your project, and they have [lesson format](https://github.com/CodeClub/lesson_format) which might be perfect for us. That would only solve my specific issue though, and it's a _maybe_. But I was trying to show examples of how useful it is with independent modules available on `npm` compared to classic "download the JS file, put it somewhere, etc", and not specifically trying to solve my own issue (although that'd be great too ofc). I don't especially see any downsides though? You already seem to use git tags so if you only add another `.0` to your version number and follow [SemVer](http://semver.org) (which is a good idea anyway) you wouldn't have to do anything special for releasing new versions. The module interface I guess would be a one time thing if it's not perfect already.

**Comment by tjvr** [comment]
@seriema added a package.json—thanks!

Should I also publish to npm? Cheers :-)

**Comment by seriema** [comment]
@tjvr That'd be great! You might want better keywords and description etc in the package.json than what I did.

**Comment by tjvr** [comment]
@seriema I don't use npm for this sort of workflow, so if you want to send another PR that'd be grand :-)

**Comment by seriema** [comment]
:+1:
