### ISSUE TITLE
Set `direction: rtl` for right-to-left languages

### ISSUE THREAD

**Issue by andylolz** [tjvr/scratchblocks#58]
[Demo](http://blob8108.github.io/scratchblocks2/#?lang=he&script=%D7%9B%D7%90%D7%A9%D7%A8%20%D7%9C%D7%95%D7%97%D7%A6%D7%99%D7%9D%20%D7%A2%D7%9C%20%40). The green flag graphic should appear on the left-hand side.

NB the information in the .po files is not reliable here – the Spanish .po file says “RTL”, which is not correct… The Arabic .po file says “RTL-math” – I’m not sure what this means. It might be preferable to just manually declare a list of RTL languages.

**Comment by andylolz** [comment]
I had a go at this [over here](https://github.com/andylolz/scratchblocks2/tree/58-rtl) by very simply adding the `direction: rtl` directive to the `<div class="sb2">` element. The text looks perfect now, but I have a few other glitches:

![screen shot 2015-01-02 at 13 37 11](https://cloud.githubusercontent.com/assets/464193/5596387/ae922344-9284-11e4-9a32-711dd78179cc.png)

Specifically, the dropdown arrows and the block indentations are both on the wrong sides.

I could either try to iron the glitches out in css, or I could try to avoid them by only applying the `direction: rtl` directive to each block (rather than to the `sb2` div).

**Comment by blob8108** [comment]
You need to apply it to individual blocks anyway, because mixing two languages (eg. English and Arabic) in one input is supported.

**Comment by andylolz** [comment]
Okay, cool. Is that feature just available on the github pages version, or also in the forum plugin?

**Comment by blob8108** [comment]
All versions. The plugin starts with English loaded, and it's not possible to un-load it. It supports multiple languages to be loaded at once, but it's intended to be used with either none or one extra language loaded.

I *think* there's a way to work out which language a block comes from *somewhere* in the parser. Maybe I should have a look sometime.

**Comment by andylolz** [comment]
> I think there's a way to work out which language a block comes from somewhere in the parser

Yeah – `find_block(…)` knows, because that information is contained within `block_by_text`. I made a start at adding `lang` to the returned `info` object. I should be able to finish this off and send a PR.

**Comment by andylolz** [comment]
Nice – that works much better:

![screen shot 2015-01-02 at 16 55 39](https://cloud.githubusercontent.com/assets/464193/5597766/3c08acf0-92a0-11e4-920a-e6c26fdb1d9e.png)

Still a problem with the RTL dropdown arrows… But it’s getting closer…

**Comment by blob8108** [comment]
Would setting all the dropdowns to LTR work?

**Comment by andylolz** [comment]
Haha yep – I realised the same thing :) PR imminent!
