### ISSUE TITLE
Translation insert order does not always match English insert order

### ISSUE THREAD

**Issue by andylolz** [tjvr/scratchblocks#64]
NB. This really only affects the generator currently.

I’ve separated this out into a new issue, as it is a little bit complicated. Discussed [a little bit here](https://github.com/blob8108/scratchblocks2/issues/33#issuecomment-67949745), and a [bit more here](https://github.com/blob8108/scratchblocks2/pull/57#issuecomment-68570409).

I’ve made [an attempt at fixing the translations](https://github.com/andylolz/scratchblocks2/compare/andylolz:master...64-variable-order) and [fixing the generator code](https://github.com/andylolz/scratchblocks2/compare/andylolz:gh-pages...64-fix-generator) but it’s probably buggy.

Note that this code finds 111 translation strings with reordered inserts. It turns out the translation .po files are quite buggy, so it currently ducks out if anything looks awry e.g. variable names don’t match up.

**Comment by blob8108** [comment]
Your fix looks hacky, so I was hoping to first switch to using `%`-strings instead of underscores `_` internally, before doing a proper fix of this. But I don't have time to do that, so could you please send a PR for this for me to test? Thanks!

**Comment by blob8108** [comment]
> please send a PR for **this**

Whoops: I meant _your_ fix, not my proposed solution!

But I have a little time now, so I'll have a look at fixing this properly…

**Comment by blob8108** [comment]
Having thought about all the possible solutions, I think it's easiest just to merge your fix. Can you please send me a PR for it? Thanks! :)

**Comment by tjvr** [comment]
We've now switched to using proper block specs instead of underscores, which should make this easier to fix.

**Comment by tjvr** [comment]
Hmm, having looked into this I can't find any examples of blocks with reordered inserts. Maybe there was a bug in your script?

Additionally, the new way of implementing RTL seems to fix this :)

<img width="292" alt="screen shot 2016-04-22 at 09 59 19" src="https://cloud.githubusercontent.com/assets/639289/14736946/95ea6f0e-0871-11e6-8f22-44e9ea3ce91d.png">

Feel free to comment/raise a new issue in future if there's still a problem.
