### ISSUE TITLE
General purpose scratchblocks babelfish

### ISSUE THREAD

**Issue by andylolz** [tjvr/scratchblocks#65]
This cool idea was [proposed by @blob8108](https://github.com/blob8108/scratchblocks2/issues/33#issuecomment-33995521) and inspired by @pseudobjorn.

I’ve made a rough demo version here:
http://scratchblocks.codeclub.org.uk/translator

**Comment by andylolz** [comment]
A couple of known bugs:
 * `define` blocks don’t work correctly yet. I think I just need to handle them separately
 * We load both the “from” and “to” languages (as well as English), so if you type something using either English or the “to” language, it’ll be recognised ([example](http://scratchblocks.codeclub.org.uk/translator/#script=when%20gf%20clicked%0Arebondir%20si%20le%20bord%20est%20atteint&from=ja&to=fr)). This is a bit weird.

**Comment by blob8108** [comment]
Very cool -- thanks for working on this! Someone suggested it to me over a year ago, possibly [joooni](http://scratch.mit.edu/users/joooni), but I never got around to it.

> if you type something using either English or the “to” language, it’ll be recognised 

That's fine -- Google Translate has similar behaviour, doesn't it?

You should translate menu options too, such as `mouse-pointer`. Note this requires more strings from pootle than we've currently fetched. (The same applies to the generator, too.)

**Comment by andylolz** [comment]
> You should translate menu options too, such as mouse-pointer. Note this requires more strings from pootle than we've currently fetched. (The same applies to the generator, too.)

Good point, yes!

Quick question: Should I include these translations in `translations.js` / `translations-all.js`, or would you prefer them in a separate file? Looks like there’s about 60 of these words that haven’t been translated elsewhere.

**Comment by blob8108** [comment]
Urgh, I don't know. I regret the design of those files. For now, yeah, probably easiest just to add them to `build_translations.py`.

**Comment by andylolz** [comment]
kk I’ve done it ([and it works!](http://scratchblocks.codeclub.org.uk/translator/#script=when%20flag%20clicked%0Apoint%20in%20direction%20(0%20v)%0Ago%20to%20x%3A%20(-215)%20y%3A%20(-160)%0Aforever%0Aif%20%3C%20(distance%20to%20%5Bmouse-pointer%20v%5D)%20%3E%20%5B5%5D%20%3E%20then%0Apoint%20towards%20%5Bmouse-pointer%20v%5D%0Amove%20(1)%20steps%0Aend&from=en&to=fr)) It also involved a change to `scratchblocks2.js` ([details here](https://github.com/andylolz/scratchblocks2/compare/65-add-translations)).

**Comment by andylolz** [comment]
> probably easiest just to add them to `build_translations.py`.

So… Either way I will be modifying `build_translations.py`… I was more suggesting that I could put these additional translations in e.g. `translations-extra.js` and `translations-all-extra.js`…

Alternatively, I could just add them to `translations-all.js` and not `translations.js` (since they’re only used on the github page and not by the plugin) and then also avoid modifying `scratchblocks2.js`. In fact, I might have a go at that this evening :)

**Comment by andylolz** [comment]
Okay, I’ve made that change now. So `/translations` now no longer requires a patch to `scratchblocks2.js`, and the extra translations generated for it are not included in `translations.js`.

**Comment by andylolz** [comment]
> Urgh, I don't know. I regret the design of those files.

Out of interest, how would you do it differently? I wondered about the mixture of objects and arrays – I guess you used objects where translations were sparse, and arrays elsewhere (thereby minimising overall file size). Is that right?

**Comment by blob8108** [comment]
More or less. I was worried about file size, so I used an array that corresponds to the English blocks in `translations.js`. I've since realised a dictionary would probably be fine, since gzip would compress the repeated keys anyway, and it would make the design less brittle.

Some of them have to be dictionaries, particularly `aliases`, since there may be multiple aliases for the same block, preventing the use of an array.

**Comment by andylolz** [comment]
So… For the dropdowns, I went for an array (but happy to change this, since it means hardcoding the English versions in two different places.)

> Some of them have to be dictionaries, particularly aliases, since there may be multiple aliases for the same block, preventing the use of an array.

Ah yes, good point! Actually, this posed a bit of an issue here, since it means there’s a choice of translations for a given block (e.g. one with a ⚑ in it, one with a “grüne Flagge” in it…) At the moment, the last one we get to wins.

**Comment by tjvr** [comment]
We now have one of these at http://scratchblocks.github.io/translator/.

**Comment by tjvr** [comment]
Added "swap" button feature too
