### ISSUE TITLE
Rebuilding text into .sb2 (not an issue)

### ISSUE THREAD

**Issue by NitroCipher** [tjvr/scratchblocks#77]
Please add some way of converting the text back into an .sb2 or .sprite2 format

**Comment by tjvr** [comment]
Whatever for?

**Comment by NitroCipher** [comment]
I want to be able to use scratch as a text-based programming language is well, and it would make it easier to make custom blocks.

**Comment by tjvr** [comment]
scratchblocks is not a good syntax for that. I have a separate project for that, see <http://tjvr.org>
