### ISSUE TITLE
I can't convert projects to sb2!

### ISSUE THREAD

**Issue by DrKat123** [tjvr/scratchblocks#82]
It returns as an error whenever i convert a project

**Comment by tjvr** [comment]
What are you talking about here?

**Comment by DrKat123** [comment]
Whenever i convert a Scratch project to scratcblocks, it always returns as an error

**Comment by tjvr** [comment]
I don't understand. Closing this for now. Feel free to try and explain it better!

**Comment by DrKat123** [comment]
Yeah, i'll post a screenshot later

**Comment by DrKat123** [comment]
![huh?](http://prntscr.com/9tkhcv)
I can't convert that particular project.
