### ISSUE TITLE
Upvars?

### ISSUE THREAD

**Issue by Jonathan50** [tjvr/scratchblocks#83]
Can we have Snap*!* upvars in scratchblocks?

**Comment by tjvr** [comment]
You can already make them!

**Comment by Jonathan50** [comment]
Ok but they aren't shaded the same (it might be a bit hard to do that in CSS, though)

**Comment by tjvr** [comment]
Can't you do (( foo::variable) :: grey) ?

**Comment by Jonathan50** [comment]
But that takes up a lot of space...

**Comment by tjvr** [comment]
Can you give a screenshot showing the difference?

**Comment by Jonathan50** [comment]
![](http://i.cubeupload.com/KwUAGB.png)
![](http://i.cubeupload.com/o78sDK.png)

doing `((foo) :: grey)` takes up more space than the outline in Snap*!* and makes it look like the variable foo is an argument to the nameless grey reporter
