### ISSUE TITLE
Block named "constructor" breaks

### ISSUE THREAD

**Issue by Jonathan50** [tjvr/scratchblocks#88]
Well this is weird...
If I have
```
constructor
```
then everything stops working.
I just see the text in a monospace font (like in the mobile forums).
If I have
```
constructo
```
or
```
constructor test
```
everything works fine, but that's not what I want.

**Comment by liam4** [comment]
I can reproduce this. Using Firefox 47.0a1 (2016-02-25).

**Comment by tjvr** [comment]
I would guess we're missing a hasOwnProperty somewhere...

**Comment by Jonathan50** [comment]
Oops - I forgot to mention my browser!
Iceweasel (Parabola's slightly modified Iceweasel, actually) 43.0.


Does anybody know why Iceweasel always reports my as using WINDOWS?

**Comment by Jonathan50** [comment]
Yayyyy
