### ISSUE TITLE
Changing block colours won't work on wiki

### ISSUE THREAD

**Issue by banana439monkey** [tjvr/scratchblocks#91]
The block colours won't work on the scratch wiki. I'm trying to make a list block called (list) and it's coming out as a variable. I'm trying to get it to a list block, but it only renames the variable. 
![image](https://cloud.githubusercontent.com/assets/13748717/13663695/de8b21f2-e69a-11e5-92fc-13916972b190.png)

**Comment by tjvr** [comment]
Yeah, the version on the wiki is outdated. Bug the ST to update it.
