### ISSUE TITLE
SVG renderer draws green flag too low

### ISSUE THREAD

**Issue by liam4** [tjvr/scratchblocks#95]
SVG renderer:
![SVG renderer](https://cloud.githubusercontent.com/assets/9948030/14232409/48dd9c58-f981-11e5-8781-2a69ed3b06b1.png)

Normal renderer:
![normal renderer](https://cloud.githubusercontent.com/assets/9948030/14232410/48df09bc-f981-11e5-89a3-7c599501016d.png)

The SVG renderer draws the green flag a few pixels too close to the bottom of the hat block.

**Comment by tjvr** [comment]
(Should this have been a comment on the PR?)

Good point, thanks for reporting :) Have you tried comparing with Scratch's renderer?

**Comment by liam4** [comment]
Yeah, the scratch renderer looks like the scratchblocks renderer in this case.
