### ISSUE TITLE
Add post-render hook to renderMatching

### ISSUE THREAD

**Issue by tjvr** [tjvr/scratchblocks#96]
To resolve #30: We want a way to manipulate the element inserted into the DOM.

Possibly we should have a set of callbacks for each step? But that might be going overboard and trying to anticipate future extensions :P

**Comment by liam4** [comment]
All I find necessary is as in #30, why would there need to be an event for each step? Also, what does a 'step' refer to here? A render of a block? A stage of the rendering itself?

**Comment by tjvr** [comment]
@liam4 Yeah, that's all we need right now. But it's plausible in future we might want to manipulate the AST before rendering, or manipulate the code picked up by renderMatching.

Of course, you could always write your own version based on `parse()` and `render()`...
